apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: data-science-pipelines-artifact-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: data-science-pipelines-artifact-manager
    app.kubernetes.io/part-of: odh
  name: data-science-pipelines-artifact-manager
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    app.kubernetes.io/instance: data-science-pipelines-artifact-manager
status:
  loadBalancer: {}
