apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rest-proxy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/odh/rest-proxy@sha256:eeed989ba02c5300c97fd8913ab788658f978415dfb6c0443a740a4e089f8d68
        name: container-image
        resources: {}
status: {}
