apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: modelmesh-serving
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: modelmesh-serving
    app.kubernetes.io/part-of: odh
  name: modelmesh-serving
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: modelmesh-serving
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: modelmesh-serving
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/odh/modelmesh-serving@sha256:8fe4a884be1ca4f1cf9a4ea3572b2c507ea743ce002287bac44c1000a847673e
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 9999
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
