apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: modelmesh-serving
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: modelmesh-serving
    app.kubernetes.io/part-of: odh
  name: modelmesh-serving
spec:
  ports:
  - port: 9999
    targetPort: 9999
  selector:
    app.kubernetes.io/instance: modelmesh-serving
status:
  loadBalancer: {}
