apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: codeflare-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codeflare-operator
    app.kubernetes.io/part-of: odh
  name: codeflare-operatorwcta
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: codeflare-operator
    weight: 100
status: {}
