apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: trustyai-explainability
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: trustyai-explainability
    app.kubernetes.io/part-of: odh
  name: trustyai-explainability
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: trustyai-explainability
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: trustyai-explainability
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/odh/trustyai-explainability@sha256:c5468fc59d4448258c1e27dbd8982abc18b47f0b0bd88200c01148f25058c4f6
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
