apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kuberay-operator-kgjk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kuberay-operator-kgjk
    app.kubernetes.io/part-of: odh
  name: kuberay-operator-kgjk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kuberay-operator-kgjk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kuberay-operator-kgjk
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/odh/kuberay-operator-kgjk@sha256:c5630220b7dbf2371e7dc63852e42c3534e5fb85108a5838ba3c9a7e48746513
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
