apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: data-science-pipelines-persistence-agent
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: data-science-pipelines-persistence-agent
    app.kubernetes.io/part-of: odh
  name: data-science-pipelines-persistence-agent
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: data-science-pipelines-persistence-agent
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: data-science-pipelines-persistence-agent
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/odh/data-science-pipelines-persistence-agent@sha256:4255e2104ca7619576f82f44c318e293fdfbf0896886d6fb8782066fe3c64f6a
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8888
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
