apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: data-science-pipelines-operator-rpwv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: data-science-pipelines-operator-rpwv
    app.kubernetes.io/part-of: odh
  name: data-science-pipelines-opyqtp
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: data-science-pipelines-operator-rpwv
    weight: 100
status: {}
