apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rest-proxy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rest-proxy
    app.kubernetes.io/part-of: odh
  name: rest-proxy
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rest-proxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rest-proxy
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/odh/rest-proxy@sha256:eeed989ba02c5300c97fd8913ab788658f978415dfb6c0443a740a4e089f8d68
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
