apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kuberay-operator-kgjk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/odh/kuberay-operator-kgjk@sha256:c5630220b7dbf2371e7dc63852e42c3534e5fb85108a5838ba3c9a7e48746513
        name: container-image
        resources: {}
status: {}
