apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: data-science-pipelines-cache-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: data-science-pipelines-cache-server
    app.kubernetes.io/part-of: odh
  name: data-science-pipelines-cane2t
spec:
  path: /
  port:
    targetPort: 8888
  to:
    kind: Service
    name: data-science-pipelines-cache-server
    weight: null
status: {}
