apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: opendatahub-operator-jfl8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opendatahub-operator-jfl8
    app.kubernetes.io/part-of: odh
  name: opendatahub-operator-jfl8
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: opendatahub-operator-jfl8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: opendatahub-operator-jfl8
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/odh/opendatahub-operator-jfl8@sha256:12ca68dd4a279c97aa7df5a3bd9157b6757645067a51abe3d4b2a03765cb416c
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
