apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: opendatahub-operator-jfl8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opendatahub-operator-jfl8
    app.kubernetes.io/part-of: odh
  name: opendatahub-operator-jfl8
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: opendatahub-operator-jfl8
status:
  loadBalancer: {}
