apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-component
    app.kubernetes.io/part-of: odh
  name: my-component
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: my-component
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/odh/my-component@sha256:b287e9c777bcb19f7daeab9ace2ef61c17d3b3c520fad8ba004f57fe56387421
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
