apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: trustyai-explainability
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/odh/trustyai-explainability@sha256:1c20aa41c09a3d1e0ec9f04ff374daa6d8c978a02acf6e448d92989b716e261c
        name: container-image
        resources: {}
status: {}
