apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: modelmesh-runtime-adapter
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: modelmesh-runtime-adapter
    app.kubernetes.io/part-of: odh
  name: modelmesh-runtime-adapter
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: modelmesh-runtime-adapter
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: modelmesh-runtime-adapter
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/odh/modelmesh-runtime-adapter@sha256:4203991123e7b489ca135382a52fca96372afb25495ef4631be411333ef80a43
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
