apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: modelmesh-runtime-adapter
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: modelmesh-runtime-adapter
    app.kubernetes.io/part-of: odh
  name: modelmesh-runtime-adapter
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: modelmesh-runtime-adapter
status:
  loadBalancer: {}
