apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: data-science-pipelines-operator-rpwv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: data-science-pipelines-operator-rpwv
    app.kubernetes.io/part-of: odh
  name: data-science-pipelines-operator-rpwv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: data-science-pipelines-operator-rpwv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: data-science-pipelines-operator-rpwv
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/odh/data-science-pipelines-operator-rpwv@sha256:ea5ed5272f0135d6134f76eafb86f6b4310e220094f7b73fe13e29b9fb1bfda6
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
