apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: data-science-pipelines-operator-gjdj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: data-science-pipelines-operator-gjdj
    app.kubernetes.io/part-of: odh
  name: data-science-pipelines-operator-gjdj
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: data-science-pipelines-operator-gjdj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: data-science-pipelines-operator-gjdj
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/open-data-hub-tenant/odh/data-science-pipelines-operator-gjdj@sha256:57980b29fefbd5e029995d4f520aecbe5c1accb9b354e56aa6c47e585386193c
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
